### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by ElenaBossolini** [lovasoa/marshmallow_dataclass#101]
Hi,

thank you for a nice package. It would be nice to have `marshmallow_dataclass` distributed in the `conda-forge` channel as well, and not only with `Pypi`. 
I could see that the same issue was raised in #7 , but not sure whether it was followed up on?
I would be happy to contribue in making a `conda-recipe` for it, if needed.

**Comment by mivade** [comment]
I actually managed to build conda packages a while back (they are deployed to an internal conda channel so not public). The main difficulty as I recall were the optional dependencies since you need to also have conda packages for those (it's possible that some of those exist in conda-forge now, though).

**Comment by lovasoa** [comment]
Yes, PR welcome ! I'll publish it if someone makes the recipe and the necessary changes to CI: https://github.com/lovasoa/marshmallow_dataclass/blob/master/.travis.yml

**Comment by ElenaBossolini** [comment]
@mivade 's comment is correct, there is a challenge associated with the `[union,enum]` extras.
 > The main difficulty as I recall were the optional dependencies since you need to also have conda packages for those

I have had some discussions with my colleagues about how to handle this issue, and here are some possibilities:

1. create a conda recipe for the plain `marshmallow-dataclass` package. This would mean that when you type `conda install marshmallow-dataclass -c conda-forge`, then you do not get the extra features associated with `enum` and `union`.  The way to overcome it is then to separately install `marshmallow-enum` or `typeguard`, respectively.  
This choice has the nice feature that there is a name/content correspondence between what is on Pypi and what would be in conda-forge, for the simple case without extras. On the other hand, the UX for the developer that installs `marshmallow-dataclass` from `conda-forge` is suboptimal, since it is unclear how she/he may get the extras included.

2. create a conda recipe for the `marshmallow-dataclass` that includes all extras, i.e. writing a recipe from a skeleton of the type `conda skeleton pypi marshmallow_dataclass --all-extras`. This will make you get both the `enum` and `union` extras as soon as you install the package. Pros: there is no longer the issue of handling the extras, cons: there is no 1-to-1 name/content correspondence with what's on Pypi. 
Also, there may be some further need of creating a conda package for the `pytest-mypy-plugins` as that is not in conda-forge at the moment. So at a first glance it may seem a kind of a rabbit hole, or a lot of open source contribution :-) .  Or would it be possible to excluded `pytest-mypy-plugins` from the packaging since it is needed for the tests? If so, then this would be probably my favourite solution. 

3. Use conda's subpackages, explicitly listing the [subpackage requirements](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section). In this way we could have a trivial subpackage for the no-extras case, plus two subpackages for each of the two extras, and when calling the implicit metapackage we would have all the extras.

**Comment by lovasoa** [comment]
I think option 2 is the best. pytest-mypy-plugins is useful only when you have code that uses this library's NewType feature and you want that code to typecheck with mypy.

**Comment by ElenaBossolini** [comment]
this means that `pytest-mypy-plugins` is more used in the case of someone cloning or forking the repository from GH rather than when installing from `conda-forge`. I will simply avoid including it!

**Comment by lovasoa** [comment]
Will be fixed by https://github.com/conda-forge/staged-recipes/pull/12730

**Comment by lovasoa** [comment]
The conda package has been merged. 🎊 
https://github.com/conda-forge/staged-recipes/pull/12730#event-3814757570

Thank you @ElenaBossolini for your work !
