### ISSUE TITLE
Optional is interpreted as not required

### ISSUE THREAD

**Issue by smarie** [lovasoa/marshmallow_dataclass#102]
From https://github.com/smarie/python-marshmallow-pyfields/issues/1

it seems that a mandatory field with type hint `Optional` is today considered by method `field_for_schema` as being "not required".

However, this is not the meaning of `Optional`. `Optional` means that the type of the field is optional (= it is nonable), but does not tell anything about the fact that the field is required.

That being said this is probably an acceptable shortcut to ease life of users, so I let you decide if it is important to fix it or not :)
Thanks for the nice lib, I was able to leverage it very easily to support pyfields !

**Comment by lovasoa** [comment]
Yes, it's not a bug, it's set this way on purpose. We have to do a mapping from the python types model to the marshmallow schema model, and we chose what we thought was the most intuitive. You can propose a PR improving the documentation to make that more obvious.

**Comment by lovasoa** [comment]
Yes, it's not a bug, it's set this way on purpose. We have to do a mapping from the python types model to the marshmallow schema model, and we chose what we thought was the most intuitive. You can propose a PR improving the documentation to make that more obvious.

**Comment by smarie** [comment]
Thanks for confirming @lovasoa  ! I'm totally at ease with this choice ; not sure where to put it in the doc though..
