### ISSUE TITLE
Error serialisation of Optional field and default value set is not None

### ISSUE THREAD

**Issue by aksswami** [lovasoa/marshmallow_dataclass#108]
```python
from dataclasses import dataclass, field
from typing import List, Optional

import marshmallow_dataclass
import marshmallow.validate


@dataclass
class Building:
    # field metadata is used to instantiate the marshmallow field
    height: float = field(metadata={"validate": marshmallow.validate.Range(min=0)})
    name: str = field(default="anonymous")
    age: Optional[int] = field(default=0)

building_schema = marshmallow_dataclass.class_schema(Building)()
building_schema.load({"name": "Eiffel Tower", "height": 324, "age": None})
```

For above code I am getting this error:-
```bash
    building_schema({"name": "Eiffel Tower", "height": 324, "age": None})
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 544, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 724, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 911, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'age': ['Field may not be null.']}
```

Error is from marshmallow schema, but I am not able to find root cause of the error. Any help would be appreciated.

When `age: Optional[int] = field(default=None)` above code works.

Python 3.7
marshmallow_dataclass tried on 8.0.0 and 8.1.0
marshmallow 3.8.0

**Comment by lovasoa** [comment]
Yes, optional fields are translated to marshmallow fields with a `required` property of `False`. You can create a building without an age with `building_schema.load({ "name": "Eiffel Tower", "height": 324 })`

**Comment by aksswami** [comment]
Any way to specify have `None/null` in dict or JSON and serialize it?

**Comment by lovasoa** [comment]
I'll reopen this issue until this is solved

**Comment by noirbee** [comment]
Note that I'm afraid the fix I'm proposing in #121 might be considered as API-breaking, as some payloads that would have been rejected before will now be considered valid.

I still think this is the right way to go since this is how I expect `Optional` to behave, modeled on what it actually means for Python / MyPy: it's actually `Union[T, None]`, which means you `None` is a valid value, including when explicitly passed as a value (vs. only as a default value).

**Comment by lovasoa** [comment]
I think it's okay to accept inputs that were previously rejected without a major version bump. The opposite would be more problematic.

**Comment by kqvanity** [comment]
@lovasoa Can i allow nested attributes. I'm trying to deserialize a nested data class that's from another third-party library.
so far my current approach for top-level fields
```python
PersonSchema.fields['field-parent').allow none = True
```
