### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by liberforce** [lovasoa/marshmallow_dataclass#116]
I could have saved some time for my PR had I understood how the testing infrastructure worked, especially that pytest/mypy integration. Here's I did it:

```
virtualenv --python python3.7 venv
source venv/bin/activate
pip install --upgrade pip setuptools # otherwise pystache install fails
pip install --editable .[dev]
pre-commit install --install-hooks
```

Running tests:
```
pytest
```

**Comment by lovasoa** [comment]
We do have a section about contributing in the README. I'll update it.
