### ISSUE TITLE
typing.Mapping not supported.

### ISSUE THREAD

**Issue by carstencodes** [lovasoa/marshmallow_dataclass#120]
Marshmallow supports typing.Mapping as a generic revision of [Dict](https://github.com/marshmallow-code/marshmallow/blob/6d235205521b80ff9f75b26c2216cd8f41ef1353/src/marshmallow/fields.py#L1451).

It would be good to support Mappings in marshmallow_dataclass.

A primitive patch in [__init__.py](https://github.com/lovasoa/marshmallow_dataclass/blob/8bb24fece2774418a05393d77ee210b3bfd8a988/marshmallow_dataclass/__init__.py#L490) would be changing

```
elif origin in (dict, Dict):
```

to 

```
elif origin in (dict, Dict. collections.Mapping):
```

It works for serialization, but deserialization might produce an error.

**Comment by lovasoa** [comment]
Yes, this would be nice ! PR welcome :)

**Comment by anis-campos** [comment]
@lovasoa this one too was done in #132

**Comment by carstencodes** [comment]
@anis-campos Gee, thanks.
