### ISSUE TITLE
"data_key" parameter not working as expected

### ISSUE THREAD

**Issue by espetro** [lovasoa/marshmallow_dataclass#127]
Hi there,

Thanks for doing such a great work! I'm having some trouble understanding how this project integrates with `marshmallow`. Currently, I'm willing to load JSONs with a key name different from the one I want to use in the Python object:

```python
# imports ...

input = '''{"some-data": "marshmallow"}'''

@dataclass
class FirstTry:
    some_data: str = fields.Str(data_key="some-data")

_ = FirstTry.Schema().load(input)  # This will raise a ValidationError :( !

class SecondTry(marshmallow.Schema):
    some_data: str = fields.Str(data_key="some-data")

_ = SecondTry().load(input)  # This will work!
```

Why is this happening? I believe the behaviour should be the same, although the syntax may vary. Is there any workaround to do this with `marshmallow_dataclass`?

**Comment by lovasoa** [comment]
You can find  a full reference for how to use marshmallow-dataclass in the readme: https://github.com/lovasoa/marshmallow_dataclass#customizing-generated-fields


```py
    some_data: str = fields.Str(data_key="some-data")
```

`str` and `fields.Str` are not the same thing.

**Comment by lovasoa** [comment]
Yes, documentation PRs are more than welcome ! 🙂

**Comment by lovasoa** [comment]
We have the readme, and the doc comments with many examples. If you have ideas to make either clearer, a pr is welcome
https://lovasoa.github.io/marshmallow_dataclass/html/marshmallow_dataclass.html#module-marshmallow_dataclass
