### ISSUE TITLE
Question about inheritance 

### ISSUE THREAD

**Issue by asyd** [lovasoa/marshmallow_dataclass#134]
Hello folks, 

sorry if it's a dumb question. 

I want to embed a generic class into another one, something like:

```
from marshmallow_dataclass import dataclass, class_schema

@dataclass
class Meta:
    pass

@dataclass
class MyRealObject(Meta):
    attr1: str
    attr2: str

@dataclass
class AnotherObject(Meta):
    attr1: str
    attr2: str
    attr3: str

@dataclass
class Canister:
    subschema: str
    object: Meta

CanisterSchema = class_schema(Canister)()

my_obj = MyRealObject(attr1="test", attr2="test")
canister = Canister(subschema="test", object=my_obj)

print(canister)
print(CanisterSchema.dumps(canister))
```

Here the output:

```
Canister(subschema='test', object=MyRealObject(attr1='test', attr2='test'))
{"subschema": "test", "object": {}}
```

Off course if I replace `Meta` by `MyRealObject` in `Canister` definition it work as expected:

```
Canister(subschema='test', object=MyRealObject(attr1='test', attr2='test'))
{"object": {"attr1": "test", "attr2": "test"}, "subschema": "test"}
```

Thanks for feedbacks!

**Comment by lovasoa** [comment]
You have to define your entire schema in advance, you can't say *I will have some class there but I'm not telling you which one*. That would make de-serialization impossible.
 
What you are looking for here is [`Union`](https://docs.python.org/3/library/typing.html#typing.Union) which are supported through [the optional Union feature](https://github.com/lovasoa/marshmallow_dataclass#installation)
