### ISSUE TITLE
TypeError: list is not a dataclass and cannot be turned into one.

### ISSUE THREAD

**Issue by FranzForstmayr** [lovasoa/marshmallow_dataclass#140]
Starting with Release of Python3.9 `list` is a generic alias type and `typing.List` becomes deprectated.

However, marshmallow_dataclass is unable to work with the construct `list[SomeOtherDataclass]`, whereas `List[SomeOtherDataclass]` works.

**Comment by lovasoa** [comment]
Duplicate of https://github.com/lovasoa/marshmallow_dataclass/issues/136
