### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by markedwards** [lovasoa/marshmallow_dataclass#142]
Using `@marshmallow_dataclass.dataclass()` to decorate a class, creating an instance of that class fails to type-check as expected:
```python
@marshmallow_dataclass.dataclass
class Foo:
    foo: str


Foo(foo='bar')  # Unexpected keyword argument "foo" for "Foo"
```

I haven't dug deep enough to identify the reason for this.  Is this a known limitation?

**Comment by lovasoa** [comment]
You can use the marshmallow-dataclass mypy plugin by adding the following to your mypy config : 

```toml
[mypy]
plugins = marshmallow_dataclass.mypy
```

or just declare a normal dataclass and create the schema separately

```py
foo_schema = marshmallow_dataclass.class_schema(Foo)()
```

**Comment by markedwards** [comment]
Thanks, missed that.  Works as advertised :-)
