### ISSUE TITLE
Way to completely ignore an Optional field when dumping ?

### ISSUE THREAD

**Issue by Stepland** [lovasoa/marshmallow_dataclass#144]
Hello, first off thank you so much for making such a nice library !

I may be missing something obvious, but I'm having a hard time replicating marshmallow's original dump behavior for a field that's not required.

When using a regular marshmallow schema, if I somehow **have** to pass an object with an `a` attribute/key but don't want it to appear in the serialized output, I can use `marshmallow.missing`
```py3
>>> class Thing(Schema):
...     a = fields.String()
...
>>> Thing().dump({"a": missing})
{}
```
It's not pretty but it works ...

However the equivalent trick behaves differently with marshmallow_dataclass
```py3
>>> @dataclass
... class Thing:
...     a: Optional[str]
... 
>>> Thing.Schema().dump(Thing(a=missing))
{'a': None}
```

I don't know if this is intentional, if there's another recommended way of doing this I'd be more than happy to use that instead.

**Comment by YuvalPruss** [comment]
Also asked myself the same question. Is there a way to omit those nullable values?

**Comment by lovasoa** [comment]
You can use a post-dump method. See https://github.com/marshmallow-code/marshmallow/issues/633

**Comment by Stepland** [comment]
Welp, completely forgot about that, sorry and thanks a ton for helping !
