### ISSUE TITLE
No support for handling partial=True schemas

### ISSUE THREAD

**Issue by iburakov** [lovasoa/marshmallow_dataclass#169]
Currently there seems to be no out-of-the-box way to handle partial schemas:
```python
from marshmallow_dataclass import dataclass

@dataclass                                                                                                                             
class Foo:
    x: int
    y: str

Foo.Schema(partial=True).load({"x": 3, "y": "bar"})  # => Foo(x=3, y='bar')
Foo.Schema(partial=True).load({"x": 3})  # => TypeError: __init__() missing 1 required positional argument: 'y' 
```

The abovementioned error is raised when schema's overridden .load() function tries to make a dataclass instance out of marshmallow's dict on line 644:
https://github.com/lovasoa/marshmallow_dataclass/blob/fa6c28980ccfe45742cdc9430bfb3b737690935f/marshmallow_dataclass/__init__.py#L638-L644

Would it be useful to change this method to return marshmallow's .load() result without trying to unpack it into a dataclass for partial=True schemas? In my opinion, making a dataclass out of partial dict doesn't make much sense.

As a workaround, we're overriding the .load() method again in our codebase to achieve such behavior:
```python
from marshmallow import Schema
from typing import Mapping

class FooSchema(Foo.Schema):
    def load(self, data: Mapping, *, many: bool = None, partial: bool = None, **kwargs):
        """ Customized "load" method to skip unpacking to dataclass for partial=True schemas """
        if partial is True or self.partial is True:
            return Schema.load(self, data, many=many, partial=partial, **kwargs)
        else:
            return super().load(data, many=many, partial=partial, **kwargs)

Foo.Schema = FooSchema
Foo.Schema().load({"x": 3, "y": "bar"})  # => Foo(x=3, y='bar'), as in the previous example
Foo.Schema().load({"x": 3})  # => marshmallow's ValidationError: {'y': ['Missing data for required field.']} - schema isn't partial
Foo.Schema(partial=True).load({"x": 3})  # => {'x': 3} - schema is partial now, raw dict is loaded and returned, as anticipated
```

Is it reasonable to incorporate such support for partial=True schemas into the library itself?

**Comment by lovasoa** [comment]
I think the current behavior is reasonable, and returning a different object type when partial=True instead of raising an error would be surprising

**Comment by iburakov** [comment]
You can make it an opt-in behavior if you think it's too unintuitive.

I hope you got the message that, for example, you can't use schemas from your library to handle even standard HTTP PATCH request body deserialization right now without providing some special defaults like `None` or `MISSING` for all required fields in every schema. Not only it leads to boilerplate in every schemed dataclass making them less readable, it can also cause problems if you're generating OpenAPI docs from schemas as well.

I still consider this a serious limitation of this library, but it's up to you, of course. Thanks anyway.

**Comment by greyli** [comment]
+1 for adding support to this. I just tried to implement a [PATCH operation](https://github.com/apiflask/apiflask/blob/main/examples/dataclass/app.py#L68) with marshamllow-dataclass, then I realized it's not supported.

**Comment by dairiki** [comment]
What if we added an explicit way to get to the underlying raw `marshmallow.Schema.load`?

E.g. add a `Foo.Schema.load_to_mapping` method which returns a mapping rather than an instance of dataclass `Foo`.

Then `partial=True` could be used with `load_to_mapping` (and there is no unexpected behavior with `load` returning differing types depending on its arguments.)

(For nested schema, the new method would disable any dataclass wrapping of nested values as well, to match the way marshmallow handles `partial=True` when loading nested schema.)
