### ISSUE TITLE
Attempting to get class_schema of a dataclass with Dict field results in KT is not a dataclass and cannot be turned into one

### ISSUE THREAD

**Issue by stephenbrannen** [lovasoa/marshmallow_dataclass#181]
Using 8.5.3

```
from dataclasses import dataclass
from typing import Dict
from marshmallow_dataclass import class_schema


@dataclass
class Test:
    id: int
    name: str
    env: Dict

test_schema = class_schema(Test)
```

This results in the following error:
```
File "path/to/marshmallow_dataclass/__init__.py", line 345, in _internal_class_schema
    f"{getattr(clazz, '__name__', repr(clazz))} is not a dataclass and cannot be turned into one."
TypeError: KT is not a dataclass and cannot be turned into one.
```

If the Dict type is removed or changed to dict, there is no issue generating schema.

**Comment by stephenbrannen** [comment]
I like being able to add the additional typing for the keys and values that Dict provides.

**Comment by EloiZalczer** [comment]
Up, I'm having the same issue which basically makes marshmallow_dataclass unusable with dict fields for python 3.8 and below.

**Comment by dairiki** [comment]
> For anyone having the issue, it is currently possible to avoid it by adding parameters to the Dict (i.e. Dict[Any, Any]).

Or by using `dict` instead of `Dict`.
