### ISSUE TITLE
Parameters of EnumField are ignored when loading a schema

### ISSUE THREAD

**Issue by Grennith** [lovasoa/marshmallow_dataclass#199]
https://github.com/lovasoa/marshmallow_dataclass/blob/ad4d654561a8f6514f7ee63e90642ee3417ccf3f/marshmallow_dataclass/__init__.py#L716

If a field is declared as follows, the line referenced above drops the parameters default and by_value (and any other parameters specified).
```python3
some_field: SomeEnum = EnumField(enum=SomeEnum, default=SomeEnum.FOO, by_value=True)
```

One quick workaround would be to check for the type of `default` as it already is an EnumField. There's no reason to instantiate one again dropping all parameters imho:
```python3
    if isinstance(typ, EnumMeta):
        import marshmallow_enum
        return default if isinstance(default, marshmallow_enum.EnumField) \
            else marshmallow_enum.EnumField(typ, **metadata)
```

Could be related to https://github.com/lovasoa/marshmallow_dataclass/issues/166 and https://github.com/lovasoa/marshmallow_dataclass/issues/117

**Comment by dairiki** [comment]
I think this is a dup of #228 (or vice versa).

Note that:

```py
@dataclass
class SomeData:
    some_field: SomeEnum = EnumField(...)
```

is not correct.

Correct usage would be, e.g.:

```py
@dataclass
class SomeData:
    some_field: SomeEnum = dataclasses.field(default=SomeEnum.FOO, metadata={"by_value": True})
```

I don't think this is a bug, so I'm closing this.  If conditions warrant, please comment on and reopen #228.
