### ISSUE TITLE
code in readme fails ?

### ISSUE THREAD

**Issue by asmodehn** [lovasoa/marshmallow_dataclass#20]
I m just getting familiar with marshmallow_dataclass and the code on the README fails for me me with  : 

```
line 23, in <module>
    {"name": "Eiffel Tower", "height": 324}
TypeError: cannot unpack non-iterable City object
```

My python version is Python 3.7.2

Is it included in the doctests running on travis somehow ?
I see all builds passing there... or is the code in README not uptodate ?

Thanks !

**Comment by lovasoa** [comment]
Which version of marshmallow-dataclass are you using ? It looks like you are using the pre-version but running examples from the stable version.

In marshmallow 3 (that has no stable versions published yet), `Schema().load` returns directly the object that was loaded. In marshmallow 2, it returns a tuple of `(parsed_object, error)`.

[See the available versions on PyPI](https://pypi.org/project/marshmallow-dataclass/#history).
See also marshmallow-code/marshmallow#1154. marshmallow 3 has been there for over one year now, but it still does not have a stable version.

**Comment by asmodehn** [comment]
Indeed I was, thanks for pointing it out.
using prereleases, my venv had : 
marshmallow-dataclass==6.0.0rc2
  - marshmallow [required: >=3.0.0rc4,<4.0, installed: 3.0.0rc6]
using specific 0.6.5 the readme example code works fine.
