### ISSUE TITLE
marshmallow_dataclass.class_schema() breaks classes

### ISSUE THREAD

**Issue by LostInDarkMath** [lovasoa/marshmallow_dataclass#218]
Hi there! I run into a strange problem with your package. Consider the following minimal example:

```python
from dataclasses import dataclass

import marshmallow_dataclass


class String(str):
    def revert(self) -> 'String':
        return String(self[::-1])


@dataclass
class Foo:
    value: String


if __name__ == '__main__':
    foo = Foo(value=String('hello world'))
    print(String('hello'))
    schema_body = marshmallow_dataclass.class_schema(clazz=Foo)

    String('hello')  # Error: String.__init__() takes 1 positional argument but 2 were given

```

After the call `marshmallow_dataclass.class_schema(clazz=Foo)` I'm no longer able to instantiate my `String` class. The debugger says that the `String__init__` method was changed from a `<slot wrapper '__init__' of 'object' objects>` to `<function String.__init__ at 0x7f0dce2f5c60>`. 

That raises some questions:
1. Why does `marshmallow_dataclass.class_schema(clazz=Foo)` manipulate the class `String`? 
2. Can you fix this behavior please?

## Context:
- Python 3.10.6
- marshmallow-dataclass 8.5.9
- Ubuntu 22

**Comment by LostInDarkMath** [comment]
Okay, thanks to the warning of your package I found a nice solution for this :)

## The warning I got
```
UserWarning: ****** WARNING ****** marshmallow_dataclass was called on the class <class '__main__.MyString'>, which is not a dataclass. It is going to try and convert the class into a dataclass, which may have undesirable side effects. To avoid this message, make sure all your classes and all the classes of their fields are either explicitly supported by marshmallow_dataclass, or define the schema explicitly using field(metadata=dict(marshmallow_field=...)). For more information, see https://github.com/lovasoa/marshmallow_dataclass/issues/51 ****** WARNING ******
```

## Complete working example
```python
from dataclasses import dataclass, field
from typing import TypeVar, Generic

import marshmallow_dataclass
from marshmallow.fields import String

T = TypeVar('T')


class MyString(str):
    def revert(self) -> 'MyString':
        return MyString(self[::-1])


class MyField(String, Generic[T]):
    def _deserialize(self, value, attr, data, **kwargs) -> T:
        type_ = self.__orig_class__.__args__[0]

        if not isinstance(value, type_):
            value = type_(value)

        return value


@dataclass
class Foo:
    value: MyString = field(metadata=dict(marshmallow_field=MyField[MyString]()))


if __name__ == '__main__':
    foo = Foo(value=MyString('hello world'))
    print(MyString('hello'))
    schema_body = marshmallow_dataclass.class_schema(clazz=Foo)

    MyString('hello')
```

Maybe this will help someone who encounter the same problem :)

**Comment by dairiki** [comment]
As you figured out, the root of the problem is that `class_schema` does not, by default, know anything about (e.g. how to serialize/deserialize) your `MyString` class.  When `class_schema` encounters an unknown class type, as a last-ditch effort to convert it to something it can handle (for reasons I'm not completely sure of) it tries to convert it to a dataclass.

Note that if you have a lot of `MyString` (or other types unknown to `class_schema`) fields in your dataclass(es), an alternative to specifying the marshmallow field type in a `field()` on each of them is to use a custom base schema class with a [custom TYPE_MAPPING](https://github.com/lovasoa/marshmallow_dataclass#custom-mapping-between-classes-and-fields) to define a mapping between your types and marshmallow Field types.

**Comment by LostInDarkMath** [comment]
Thank you very much @dairiki! That makes the code base indeed more clean.

Here is the complete working example for this approach:

```python
from dataclasses import dataclass
from typing import TypeVar, Generic

import marshmallow
import marshmallow_dataclass
from marshmallow.fields import String

T = TypeVar('T')


class MyString(str):
    def revert(self) -> 'MyString':
        return MyString(self[::-1])


class MyField(String, Generic[T]):
    def _deserialize(self, value, attr, data, **kwargs) -> T:
        type_ = self.__orig_class__.__args__[0]

        if not isinstance(value, type_):
            value = type_(value)

        return value


class MyBaseSchema(marshmallow.Schema):
    TYPE_MAPPING = {MyString: MyField[MyString]}


@dataclass
class Foo:
    value: MyString


if __name__ == '__main__':
    foo = Foo(value=MyString('hello world'))
    print(MyString('hello'))
    schema_body = marshmallow_dataclass.class_schema(clazz=Foo, base_schema=MyBaseSchema)

    MyString('hello')
```
