### ISSUE TITLE
Cannot add marshmallow metadata to list items

### ISSUE THREAD

**Issue by rusnyder** [lovasoa/marshmallow_dataclass#23]
## Issue

I can't seem to find any way to apply validation to items of a list type object, and upon inspection of the `field_for_schema` implementation I don't think this is possible, as no metadata is forwarded to the schema creation for the list item type:

### marshmallow_dataclass: [__init__.py](https://github.com/lovasoa/marshmallow_dataclass/blob/master/marshmallow_dataclass/__init__.py#L303)
```python
239:  def field_for_schema(
240:          typ: type,
241:          default=marshmallow.missing,
242:          metadata: Mapping[str, Any] = None
243:  ) -> marshmallow.fields.Field:
...
303:      if origin in (list, List):
304:          list_elements_type = typing_inspect.get_args(typ, True)[0]
305:          return marshmallow.fields.List(
306:              field_for_schema(list_elements_type),  # <<< No metadata passed
307:              **metadata
308:          )
```

## Current State

Let's say I have a `User` class and and want to maintain a list of email addresses for each user.  Currently, the only way I'd be able to validate the IP addresses is with a callable that iterated over the list and manually invoked Marshmallow's validators:

```python
from typing import List
from marshmallow.validate import Email
from marshmallow_dataclass import dataclass

@dataclass
class User:
    name: str
    emails: List[str] = field(metadata={
        'validate': lambda l: all(Email()(i) for i in l)
    })
```

...which, admittedly, is pretty simple, but it's more weakly representative of the validator's intent, particularly for tools that post-process the schema (i.e. - the fact that it's a list validator means that tools aren't able to recognize that the validation actually applies to the list item).

## Proposal

I'd like to add a mechanism for explicitly passing metadata to the list item schema.  I figure using a key in the `metadata` dict that doesn't conflict with Marshmallow schema kwargs would work just fine for this purpose:

```python
from typing import List
from marshmallow.validate import Email
from marshmallow_dataclass import dataclass

@dataclass
class User:
    name: str
    emails: List[str] = field(metadata={
        'item_metadata': {
            'validate': Email()
        }
    })
```

If this sounds like something of interest, I'll gladly whip it up and put out a PR.

**Comment by lovasoa** [comment]
Hello, and thank you for this detailed feature request !
I understand the use case, but I'm not a huge fan of the `metadata={'item_metadata': {...}}` syntax.
What would you think about something like :

```py
from typing import List
from marshmallow_dataclass import dataclass, NewType

IP = NewType('IP', str, validate=my_validation_function)

@dataclass
class Company:
    name: str
    ipv4s: List[IP]
```

It seems more generic, and more readable.

**Comment by rusnyder** [comment]
> It seems more generic, and more readable. The IP type would be usable on its own.

Couldn't agree more - your suggestion is much cleaner and more composable.  If I get the time to in the next few days I'll take a pass at implementing the above in a stable + prerelease-compatible way, but otherwise may wait along w/ you until Marshmallow 3 drops.

**Comment by lovasoa** [comment]
I published a new version that should fix this issue. Please try it :) [see my other comment](https://github.com/lovasoa/marshmallow_dataclass/issues/16#issuecomment-530390200)

**Comment by lovasoa** [comment]
Version 6.1.0 was just released with support for NewType, so I am closing this.
https://pypi.org/project/marshmallow-dataclass/6.1.0/

**Comment by rusnyder** [comment]
Sorry for the delay in getting back, here, but this works perfectly.  Thanks for the update!
