### ISSUE TITLE
"dump" ignores validation

### ISSUE THREAD

**Issue by rayrapetyan** [lovasoa/marshmallow_dataclass#254]
Seems Schema().dump ignores all kind of validation, e.g. given code below:

```
import dataclasses
from marshmallow_dataclass import dataclass

class Animal:
    color: str
    age: int

@dataclass
class AnimalDTO:
    color: str = dataclasses.field(metadata={'required':True})
    age: int = dataclasses.field(metadata={'required':True})
    foo: str = dataclasses.field(metadata={'required':True})

a = Animal()
a.color = "green"
a.age = 34

a_dct: dict = AnimalDTO.Schema().dump(a)
print(a_dct)
```

"a" misses field foo defined in AnimalDTO, but dump passes successfully just ignoring the foo field. It looks like dump is always succeeding no matter what...

**Comment by dairiki** [comment]
> Since this library is built on-top of Marshmallow, it probably inherits Marshmallow's dump behavior.

This is the correct answer.  Marshmallow schemas (which is what marshmallow_dataclass constructs) do not validate on serialization.  (The model is: untrusted user data is validated when deserialized, after which the python-side data --- including that constructed programmatically --- is assumed to be valid.

Closing.
