### ISSUE TITLE
Allow custom BaseSchema

### ISSUE THREAD

**Issue by manmime** [lovasoa/marshmallow_dataclass#26]
Without marshmallow_dataclass:
I have my own BaseSchema, that (not only) converts all snake_case variable names to their camelCase alternatives when dumping. All my others schemas inherit from that. 
I want to get rid of boilerplate schemas for my dataclasses and use this library, but i can't find a way to do so.

My idea:
With marshmallow_dataclass:
It would be great, if 
`PersonSchema = marshmallow_dataclass.class_schema(Person)` had a parameter `base_class=MyBaseClass`

**Comment by lovasoa** [comment]
Looks like a useful new feature. @manmime, would you be interested in making a pull request for that ? 

You would have to update [`_base_schema`](https://github.com/lovasoa/marshmallow_dataclass/blob/master/marshmallow_dataclass/__init__.py#L362), and add optional parameters to `dataclass`, `add_schema` and `class_schema`

**Comment by lovasoa** [comment]
Fixed by #28
