### ISSUE TITLE
The release workflow (to push to PyPI) is broken

### ISSUE THREAD

**Issue by dairiki** [lovasoa/marshmallow_dataclass#270]
The [release workflow] currently fails with:

> HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/  User 'lovasoa' does not have a verified primary email address. Please  add a verified primary email before attempting to upload to PyPI. See  https://pypi.org/help/#verified-email for more information.

[release workflow]: https://github.com/lovasoa/marshmallow_dataclass/actions/runs/9635658818

**Comment by lovasoa** [comment]
![image](https://github.com/lovasoa/marshmallow_dataclass/assets/552629/51efae30-3325-4fb0-96ba-b090ffc68497)

Ok, my email should be verified now; thanks for raising this @dairiki

**Comment by dairiki** [comment]
@lovasoa Thank you.  That seems to have done the trick!
