### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by sloria** [lovasoa/marshmallow_dataclass#29]
Nice work with this project!

Just a few suggestions for naming:

* "dataclasses" should be plural, for consistency with the stdlib's `dataclasses` 
* Use `-` instead of `_` in the package name. It's the de facto standard and IIRC, pip automatically normalizes `_` to `-` anyway.

So I recommend renaming to `marshmallow-dataclasses`.

Or--if you'd prefer more cleverness--I also like `schemaclasses`.

```python
from schemaclasses import schemaclass

@schemaclass
class Artist:
    name: str
```

**Comment by lovasoa** [comment]
I'm not sure this would justify breaking compatibility. This package is already known as `marshmallow_dataclass`, so I'd rather not confuse existing users.

**Comment by sloria** [comment]
Fair enough; I agree it's probably not worth the breaking change unless it was accompanied by a big API rewrite or something like that.

FWIW, the `_` can still be changed to a `-` without breakage. I did this for [aiohttp-utils](https://github.com/sloria/aiohttp-utils) to follow suit with the rest of the [aio-libs](https://github.com/aio-libs) (which previously used underscores). If you'd like, I can do the rename in the documentation with my upcoming docs PR.
