### ISSUE TITLE
Example in readme not a valid

### ISSUE THREAD

**Issue by heckad** [lovasoa/marshmallow_dataclass#41]
This example
```
import marshmallow
import marshmallow_dataclass


class UppercaseSchema(marshmallow.Schema):
    """A Schema that marshals data with uppercased keys."""

    def on_bind_field(self, field_name, field_obj):
        field_obj.data_key = (field_obj.data_key or field_name).upper()


class Sample:
    my_text: str
    my_int: int


SampleSchema = marshmallow_dataclass.class_schema(Sample, base_schema=UppercaseSchema)

Sample.Schema().dump(Sample(my_text="warm words", my_int=1))
```
not work with last version of `marshmallow_dataclass`.

**Comment by sloria** [comment]
The ‘base_schema’ param is on master but is not yet released.

**Comment by heckad** [comment]
I need to add the set of required filed. Last time you suggested [it](https://github.com/marshmallow-code/marshmallow/pull/1297#issuecomment-525305020). How to apply it for dataclasses?

**Comment by lovasoa** [comment]
This feature is available in the latest prerelease (6.1.0rc1) https://pypi.org/project/marshmallow-dataclass/#history

When you install it and test it, please come back here and give your feedback. We are waiting for enough users to test it before we stabilize the API.

**Comment by lovasoa** [comment]
I am closing it because it's not an open issue with the project, but please keep commenting here if you have a feedback to give. I'll release 6.1.0 in the coming weeks if noone raises any issue with the feature.

**Comment by heckad** [comment]
`Sample.Schema()` maybe should `SampleSchema()`. Without dot.

**Comment by lovasoa** [comment]
I am not sure what you mean by *this feature is unavailable in 6.1.0rc1*. But you are right that there is a problem with the README example. I am going to fix it. Thanks.

**Comment by heckad** [comment]
Just try tun example on 6.1.0rc1 version. You got `TypeError`.

**Comment by lovasoa** [comment]
Oh sorry, I got confused between this feature and `NewType` declarations. Let me make an rc2.

**Comment by lovasoa** [comment]
https://pypi.org/project/marshmallow-dataclass/6.0.0/#history

**Comment by heckad** [comment]
When will new version release?

**Comment by lovasoa** [comment]
I am going to make the release today

**Comment by lovasoa** [comment]
Done :smiley: https://pypi.org/project/marshmallow-dataclass/6.1.0/
