### ISSUE TITLE
Dataclasses do not implement __iter__, causing webargs.use_kwargs to fail

### ISSUE THREAD

**Issue by CptSpaceToaster** [lovasoa/marshmallow_dataclass#42]
webargs will attempt to combine the results of schema.load into the resulting kwargs to be passed into a function, as seen here:

https://github.com/marshmallow-code/webargs/blob/5.5.1/src/webargs/core.py#L446-L448

In order to repair this assumption, while still using dataclasses, I had to implement a mixin for my dataclasses to allow them to appear as iterables for the purposes of `kwargs.update(dataclass)`

```python
class Iterable:
    def __iter__(self):
        """When extending a dataclass, yields all key value pairs as if it were a dictionary"""
        for attr, value in self.__dict__.items():
            if value is not None:
                yield attr, value

@dataclass
class Building(Iterable):
    # field metadata is used to instantiate the marshmallow field
    height: float = field(metadata={"validate": marshmallow.validate.Range(min=0)})
    name: str = field(default="anonymous")
```

Should I go make noise over in webargs saying they should accept dataclasses? or is this something that we can safely hack in here, as we're are actively transforming the resulting dictionary INTO a dataclass.

Another acceptable solution would be to add a meta argument to allow a developer to skip the `post_load` step, and allow `load` to return a dictionary and NOT a dataclass, which is honestly more optimal IMO.

**Comment by lovasoa** [comment]
The whole point of this library is to let you use typed objects instead of dicts. If you convert the result back to a dict and use that, you lose a lot of the advantages. I would open a feature request in webargs...

**Comment by sloria** [comment]
I don't think it's something we'll add in webargs either (maintainer speaking). It's not intuitive for object attributes to be transformed to kwargs.

@CptSpaceToaster  I think your best bet would be to use a custom base schema class that overrides `make_data_class`, as suggested in https://github.com/lovasoa/marshmallow_dataclass/pull/43#issuecomment-538723437

**Comment by lovasoa** [comment]
@sloria : I agree that transforming the object back into a dict does not make much sense, but what would you think about supporting schemas with a custom `post_load` in webargs ?

That would allow nice, readable, and typed checked web server code, like:

```py

@dataclass
class Person:
  name: str

@app.route("/")
@use_args(Person.Schema)
def index(person):
    return "Hello " + person.name
``` 

Can I open a feature request on [marshmallow-code/webargs](https://github.com/marshmallow-code/webargs) about this ?

**Comment by sloria** [comment]
That should already work. @CptSpaceToaster can you try that out?

**Comment by CptSpaceToaster** [comment]
It looks fine for now!

```
from flask import Flask
from marshmallow_dataclass import dataclass
from webargs.flaskparser import use_args
from typing import Optional

app = Flask(__name__)

@dataclass
class Person:
  name: Optional[str] = "World"

@app.route("/", methods=['POST'])
@use_args(Person.Schema)
def index(person: Person):
    return "Hello " + person.name
```

It definitely wasn't on my radar to move away from `use_kwargs` but I can't come up with anything that would be break this yet. I guess you'll hear from me if there's an issue.
