### ISSUE TITLE
Support for attrs

### ISSUE THREAD

**Issue by jtrakk** [lovasoa/marshmallow_dataclass#44]
I like to use the [attrs module](http://attrs.org). Attrs functionality is a superset of dataclasses, though a few of the names are different (e.g. `factory` vs `default_factory`). How would you feel about having support for `attrs` in addition to `dataclasses`?

**Comment by lovasoa** [comment]
I personnally think this would be better achieved in a different project. I am not sure a lot of code could be shared anyway...

**Comment by sloria** [comment]
There's a fork of this project for attrs: https://github.com/adamboche/marshmallow-attrs

**Comment by lig** [comment]
@lovasoa FYI, the project suggested above and all similar projects are abandoned :(

You're our only hope...

**Comment by lovasoa** [comment]
@lig, no YOU are your only hope ! I am not interested in creating, using, or maintaining such a project. If you need it, then you should maintain it :)

**Comment by sloria** [comment]
@lig Have you seen https://github.com/python-desert/desert? It also supports attrs and looks to be maintained.

**Comment by lig** [comment]
> @lig, no YOU are your only hope ! I am not interested in creating, using, or maintaining such a project. If you need it, then you should maintain it :)

I might consider contributing the attrs support. Personally, I think it would be beneficial to have attrs and dataclasses being supported by the same project of this kind.
