### ISSUE TITLE
supporting generic types without type arguments, such as `dict`

### ISSUE THREAD

**Issue by vvoody** [lovasoa/marshmallow_dataclass#49]
Hi, `variables` is a dict. My dataclass NewReqPayload cannot be dumped.

```python
from dataclasses import dataclass
import marshmallow_dataclass

@dataclass
class NewReqPayload:
    category: str
    type: str
    subtype: str
    short_description: str
    description: str
    requested_by: str
    assigned_to: str
    requested_due_date: str
    variables: dict

NewReqPayloadSchema = marshmallow_dataclass.class_schema(NewReqPayload)

req_payload = NewReqPayload(
        category="System Administration",
        type="Configuration Requests",
        subtype="Tools/Automation",
        short_description="jon short_description",
        description="jon description",
        requested_by="xiaojuwang",
        assigned_to="xiaojuwang",
        requested_due_date="2019-12-20",
        variables={"environment": "development"}
)

NewReqPayloadSchema().dump(req_payload)
```

This code raises `TypeError: dict is not a dataclass and cannot be turned into one.`.

**Comment by lovasoa** [comment]
Hello and thank you for your bug report.

The best way to declare a dict field is (if your dict contains str as keys and values, as in your example):

```py
from typing import Dict

class NewReqPayload:
    variables: Dict[str, str]
```

@sloria  : What is your opinion about supporting generic types without parameters, such as `dict`, `list`, etc. ?

**Comment by sloria** [comment]
`dict` should generate `fields.Dict()` or `fields.Dict(fields.Raw(), fields.Raw())`. `list` should generate `fields.List(fields.Raw())`.

**Comment by lovasoa** [comment]
OK, so let's build that ! Who wants to make a pull request ?
