### ISSUE TITLE
Mypy error: Variable "Email" is not valid as a type mypy(error)

### ISSUE THREAD

**Issue by chespinoza** [lovasoa/marshmallow_dataclass#50]
Taking the example from the readme:

```python
import marshmallow
from marshmallow_dataclass import NewType

Email = NewType("Email", str, field=marshmallow.fields.Email)
```

When using Email in a schema, for instance:

```python
@marshmallow_dataclass.dataclass
class MySchema:
    id: str = field(metadata={"validate": marshmallow.validate.uuid})
    email: Email
    Schema: ClassVar[Type[marshmallow.Schema]] = marshmallow.Schema
```
I'm getting this error from mypy:

`Mypy error: Variable "Email" is not valid as a type mypy(error)`

versions:
```
marshmallow==3.2.1
marshmallow-dataclass==7.0.0
```
Thanks in advance.

**Comment by lovasoa** [comment]
Correct me if I'm wrong, but don't think this is related to `marshmallow_dataclass`. mypy cannot handle any dynamically created types.

Your code can be reduced to the following, that mypy also rejects:

```python
from typing import Type

Email: Type[str] = str

class MySchema:
    email: Email
```

This also gives: ` error: Variable "Email" is not valid as a type`

**Comment by lovasoa** [comment]
I opened an issue at mypy, and they do not seem to be keen on implementing anything that would allow us make `NewType` work with mypy:
https://github.com/python/mypy/issues/7901

I am going to leave this issue open, and if anyone is interested in writing a mypy plugin, we'll track progress here.

**Comment by tomdottom** [comment]
> Correct me if I'm wrong, but don't think this is related to `marshmallow_dataclass`. mypy cannot handle any dynamically created types.
> 
> Your code can be reduced to the following, that mypy also rejects:
> 
> ```python
> from typing import Type
> 
> Email: Type[str] = str
> 
> class MySchema:
>     email: Email
> ```
> 
> This also gives: ` error: Variable "Email" is not valid as a type`

`mypy` is able to recognize the following

```python
from typing import NewType

Email = NewType("Email", str)

class MySchema:
    email: Email
```

Instead of returning a function maybe `marshmallow_dataclass.NewType` could construct and return a new [Field Class](https://marshmallow.readthedocs.io/en/stable/custom_fields.html#creating-a-field-class)

**Comment by lovasoa** [comment]
> A) Return a typing.NewType and internally map this to construction functions which can be looked as needed.

This is not possible. The logic for `typing.NewType` is hardcoded in mypy and does not support dynamic arguments. See the mypy issue I linked to above. 

> B) Construct and return a new Field Class.

This wouldn't work with the rest of `marshmallow-dataclass`. In particular, this wouldn't allow:

```py
class MySchema:
    email: Email
```

**Comment by lovasoa** [comment]
@tomdottom : Would you be interested in writing a mypy plugin ?

**Comment by selimb** [comment]
I'd like for this to get fixed as well.
Wrote mypy plugin in #55
