### ISSUE TITLE
Test the mypy plugin on windows

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/marshmallow_dataclass#57]
Since @selimb added support for mypy plugin tests on windows in https://github.com/typeddjango/pytest-mypy-plugins/pull/14 , we'll be able to remove this condition in setup.py as soon as a new version of pytest-mypy-plugins comes out : 

https://github.com/lovasoa/marshmallow_dataclass/blob/master/setup.py#L27

**Comment by selimb** [comment]
@lovasoa pytest-mypy-plugins 1.2.0 was just released!
