### ISSUE TITLE
Using mypy with marshmallow_dataclass

### ISSUE THREAD

**Issue by karlb** [lovasoa/marshmallow_dataclass#6]
When checking a simple test program with mypy
```python
from marshmallow_dataclass import dataclass

@dataclass
class Foo:
    bar: int

Foo(bar=1)
```
I get the following errors
```
$ mypy type_ex.py
type_ex.py:1: error: Cannot find module named 'marshmallow_dataclass'
type_ex.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
type_ex.py:9: error: Unexpected keyword argument "bar" for "Foo"
```

I can easily silence the first error with ` --ignore-missing-imports`, but probably that is related to why I get the second error. Do I have to do any additional mypy setup do get this to validate?

**Comment by lovasoa** [comment]
For the first error: it looks like there is work to do to make a mypy compliant package. PR are welcome ! https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages

As for the second error, I think mypy is not clever enough to treat marshmallow_dataclass.dataclass the same as dataclasses.dataclass. You have to use the [`add_schema` decorator](https://lovasoa.github.io/marshmallow_dataclass/html/marshmallow_dataclass.html#marshmallow_dataclass.add_schema) or the [`class_schema` function](https://lovasoa.github.io/marshmallow_dataclass/html/marshmallow_dataclass.html#marshmallow_dataclass.class_schema) for mypy to understand what you are doing.

**Comment by karlb** [comment]
Using `add_schema` works fine. Thanks! I thought it was supposed to work with `marshmallow_dataclass.dataclass` and mypy checking, so I was afraid that I'm missing something important.

Since I'm using `--ignore-missing-imports` anyway and don't have any experience with providing PEP 561 compliant packages, I probably won't provide such a PR anytime soon.

**Comment by lovasoa** [comment]
I am closing this since #10 fixed the first part of this issue, and the second part (*Unexpected keyword argument*) cannot be fixed on our side.

**Comment by spapinistarkware** [comment]
I think this is a fix for the second part:

from mypy.plugins import dataclasses
from mypy.plugin import Plugin


def plugin(version: str):
    return FixMarshamallowDataClassPlugin


class FixMarshamallowDataClassPlugin(Plugin):
    def get_class_decorator_hook(self, fullname: str):
        from mypy.plugins import attrs
        from mypy.plugins import dataclasses

        if fullname == 'marshmallow_dataclass.dataclass':
            return dataclasses.dataclass_class_maker_callback
        return None

You can probably add it to the current plugin

**Comment by lovasoa** [comment]
@spapinistarkware Pull request welcome !

**Comment by rayrapetyan** [comment]
The way to resolve this in 2024:

In pyproject.toml add:
```
[tool.mypy]
...
plugins = "marshmallow_dataclass.mypy"
```
If using pre-commit-config, in .pre-commit-config.yaml add:
```
- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          marshmallow_dataclass,
        ]
```
