### ISSUE TITLE
How to serialize Decimal to string in collection?

### ISSUE THREAD

**Issue by heckad** [lovasoa/marshmallow_dataclass#64]
This didn't work

```
@dataclass
class Model:
    values: List[Decimal] = field(metadata={'as_string': True})
```

**Comment by lovasoa** [comment]
this is because as_string has to be set on the Decimal, not the List. You could use a NewType to achieve what you want. See the readme.

**Comment by heckad** [comment]
I wrote the new type `Decimal = NewType("Decimal", _Decimal, field=marshmallow.fields.Decimal, metadata={'as_string': True})` but it didn't help.

**Comment by lovasoa** [comment]
As explained in the [README](https://github.com/lovasoa/marshmallow_dataclass#custom-newtype-declarations) : 

> Keyword arguments to NewType are passed to the marshmallow field constructor.

You are passing the dict `metadata` to your field instead of the boolean `as_string`.
There is no `metadata` argument to `NewType`

**Comment by heckad** [comment]
Thanks grate!
