### ISSUE TITLE
Conda package? marshmallow 3.0?

### ISSUE THREAD

**Issue by aldanor** [lovasoa/marshmallow_dataclass#7]
Hi, and thanks for a nice package :)

A few quick questions - would it be worth pushing this to conda-forge to make it more discoverable? Would be nice to have it available through conda and not just pip.

Also, given that marshmallow 3.0 is bound to be out soon (the stable RCs are already out), would this package be compatible with it?

Thanks!

**Comment by lovasoa** [comment]
There is a marshmallow 3 version available on pypi. It's a pre-release: https://pypi.org/project/marshmallow-dataclass/6.0.0b7/

**Comment by lovasoa** [comment]
you can install the lastest prerelease with:
```
pip install --pre marshmallow-dataclass
```

**Comment by lovasoa** [comment]
As for the conda package, I will happily accept a pull request adding a conda package generation script.

**Comment by jadkik** [comment]
You may want to update the requirements in the `setup.py` file for the marshmallow 3 pre-releases.

I only managed to install it by using `pip install marshmallow-dataclass==6.0.0b9 marshmallow==3.0.0rc5` with a warning `marshmallow-dataclass 6.0.0b9 has requirement marshmallow<3.0,>=2.0, but you'll have marshmallow 3.0.0rc5 which is incompatible.`.

**Comment by alexlatchford** [comment]
Yeah to jump onto @jadkik's comment, thanks for making a pre-release version but it looks like there is a dependency incompatibility that'd be awesome to get ironed out.

**Comment by lovasoa** [comment]
https://pypi.org/project/marshmallow-dataclass/6.0.0rc1/

**Comment by mivade** [comment]
Since Marshmallow 3.0 is out now, can we get an official release?

**Comment by lovasoa** [comment]
Yes :)

**Comment by mivade** [comment]
Thanks!
