### ISSUE TITLE
dict-field of str to another Dataclass

### ISSUE THREAD

**Issue by Simpfally** [lovasoa/marshmallow_dataclass#73]
I want to decode this json : 

```json
{
    "ids": {
        "id124" : { "a":3 },
        "id254" : { "a":1 }
    }
}

```
and this json 

```json
{
    "ids": {
        "id132" : { "a":5 },
        "id1335":{ "a":2 },
        "id254" : { "a":1 }
    }
}

```

(so a dictionnary that maps string to a dataclass)

And I want this to fit in the same dataclass :

```python
@dataclass
class DataItem:
    a: int

@dataclass
class Data:
    ids : typing.Dict[str, DataItem]
```

Unfortunately, this doesn't work, this will return `marshmallow.exceptions.ValidationError: {'ids': ['Not a valid mapping type.']}`

How do I do this? I managed to have lists, but not dicts.

**Comment by lovasoa** [comment]
Hello,
 I cannot reproduce this error. Can you please provide a self-contained example ?

[<img width="772" alt="image" src="https://user-images.githubusercontent.com/552629/77926373-571edf00-72a6-11ea-87af-03eb472d3e9e.png">](https://colab.research.google.com/drive/1LV2IbKYmQsMJdgZidkwvccMbiDhuOZsp)

**Comment by Simpfally** [comment]
Thank you for the fast answer, I should have come here directly.

This was the self-contained example! The error is that I used @dataclass (from dataclasses module) instead of @marshmallow_dataclass.dataclass !

I don't think I saw any mention of this in the doc? https://pypi.org/project/marshmallow-dataclass/

I think it would be worth adding the correct way to use the library there.

Again thanks!

**Comment by lovasoa** [comment]
Using `dataclass` from the standard library as documented in the README works perfectly too : 

  
<img width="786" alt="image" src="https://user-images.githubusercontent.com/552629/77933347-f8119800-72ae-11ea-8ebd-2b50f0745480.png">


What error do you see in the documentation ?

**Comment by Simpfally** [comment]
I edited my answer, I did see that it also works so no problem with the documentation! I can't reproduce the error I had and now it works in my projects (I had a '=' instead of a ':' somewhere it seems, but that doesn't cause the same error)

So no errors.
