### ISSUE TITLE
Installation command not working

### ISSUE THREAD

**Issue by taidinh-tiki** [lovasoa/marshmallow_dataclass#74]
Hi author, I have tried 

> pip3 install marshmallow-dataclass[enum,union]

 but t seems not working, I think that we should change the command or fix the documentation so that user will understand it more.
Anyway, thanks for inventing this library, it helps me alot

**Comment by lovasoa** [comment]
Hello,
  What do you mean by `seems not working` ? I just tried it in a fresh venv, and it works...


```
$ pip3 install marshmallow-dataclass[enum,union]
...
$ python3
Python 3.7.3 (default, Mar  6 2020, 22:34:30)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import marshmallow_dataclass as m
>>> import typing
>>> @m.dataclass
... class C:
...   x: typing.Union[int, str]
...
>>> C.Schema.__dict__
mappingproxy({'__module__': 'marshmallow.schema', '__doc__': None, 'opts': <marshmallow.schema.SchemaOpts object at 0x107a06630>, '_declared_fields': {'x': <fields.Union(default=<marshmallow.missing>, attribute=None, validate=None, required=True, load_only=False, dump_only=False, missing=<marshmallow.missing>, allow_none=False, error_messages={'required': 'Missing data for required field.', 'null': 'Field may not be null.', 'validator_failed': 'Invalid value.'})>}, '_hooks': defaultdict(<class 'list'>, {('post_load', False): ['make_data_class']})})

**Comment by taidinh-tiki** [comment]
Hi, I don't know, it should be some problems with the terminal, so I will close it

pip3 install marshmallow-dataclass[enum,union]
zsh: no matches found: marshmallow-dataclass[enum,union]

**Comment by lovasoa** [comment]
Ok, this is your shell (`zsh`) trying to interpret the `[` as a file pattern.
I'll replace the README with `pip3 install "marshmallow-dataclass[enum,union]"`

**Comment by lovasoa** [comment]
Done, I fixed the README. Thank you for reporting this !
