### ISSUE TITLE
Calling custom code after the deserialization to a dataclass

### ISSUE THREAD

**Issue by heckad** [lovasoa/marshmallow_dataclass#78]
Missing `make_data_class` hook in `('post_load', False)`!

**Comment by lovasoa** [comment]
Hi ! 
  Can you describe your issue, and maybe give an example ?

**Comment by sloria** [comment]
The `make_data_class` was purposefully removed to address https://github.com/lovasoa/marshmallow_dataclass/issues/75 .

**Comment by heckad** [comment]
Okay, how to add hock wich call after creating dataclass object?

**Comment by lovasoa** [comment]
@heckad : What is your usecase exactly ? If you need to call code specific to the dataclass, then you should probably do it in the dataclass itself : you can use [`__post_init__`](https://docs.python.org/3/library/dataclasses.html#post-init-processing) if the code is not specific to serialization, or create a custom static function if you want to deserialize your values in a specific way.

**Comment by heckad** [comment]
I want to validate data, but I don't want to work with a dict.

**Comment by lovasoa** [comment]
If you have some invariant that should always hold for objects of your class, then `__post_init__` is probably the best place to to check them.

```python
@dataclass
class C:
  a: int
  b: int

  def __post_init__(self):
    assert self.a + self.b < 100, "a+b should be less than 100"

**Comment by heckad** [comment]
Thanks a lot for `__post_init__` method.
