### ISSUE TITLE
Nested Dataclass Support

### ISSUE THREAD

**Issue by varunsomani** [lovasoa/marshmallow_dataclass#8]
Could we have support in case we have nested dataclasses?
Something similar to what is defined here.
https://stackoverflow.com/questions/51564841/creating-nested-dataclass-objects-in-python

Is there a way we can support it in the next release?

**Comment by lovasoa** [comment]
This is already supported, and the documentation even has examples of nested dataclasses.

https://lovasoa.github.io/marshmallow_dataclass/html/marshmallow_dataclass.html#marshmallow_dataclass.class_schema

**Comment by lovasoa** [comment]
```python
@dataclass
class One:
    f_one: int
    f_two: str

@dataclass
class Two:
    f_three: str
    f_four: One
```

just works with marshmallow_dataclass
