### ISSUE TITLE
marshmallow_dataclass scheme map to flask api.model

### ISSUE THREAD

**Issue by c0x65o** [lovasoa/marshmallow_dataclass#90]
Is it possible to map a marshmallow_dataclass to a flask Namespace model? 

```
IPv4 = NewType(
    "IPv4", str, validate=marshmallow.validate.Regexp(r"^([0-9]{1,3}\\.){3}[0-9]{1,3}$")
)

@dataclass(order=True)
class Project:
    name: str = field(
        metadata=dict(description="The name of the project", load_only=True)
    )
    path: str
    title: str
    ip: IPv4
    created_date: datetime = datetime.now()
    Schema: ClassVar[Type[Schema]] = Schema 
```

I don't want to have to re-write these:
```
project = api.model('Project', fields(Project))

project = api.model('Project', {
    'path': fields.String(required=True, description='The path to the project'),
    'name': fields.String(required=True, description='The name of the project'),
    'title': fields.String(required=True, description='The title of the project'),
    'ip': fields.String(required=True, description='An ip address of the project (e.g 10.10.0.1)'),
})
```

Then I would want to do something like `@api.marshal_list_with(Project)`

**Comment by lovasoa** [comment]
Hello,
  You are not mentioning it, but I guess what you call a *flask namespace model* is actually a [flask-restplus](https://flask-restplus.readthedocs.io) model, right ?
  Marshmallow-dataclass generates (as its name suggests) marshmallow schemas. So what you are looking for is actually a way to use marshmallow schemas with create flask_restplus. A quick google search for that gives me this result: https://github.com/joeyorlando/flask-restplus-marshmallow

**Comment by c0x65o** [comment]
I am using `flask-restx`. I found this discussion:
https://github.com/python-restx/flask-restx/issues/59

So I am guessing their isn't a current way to use Marshmallow-dataclass with flask-restx
