### ISSUE TITLE
str dump accepts None

### ISSUE THREAD

**Issue by ydayan** [lovasoa/marshmallow_dataclass#94]
```
import marshmallow_dataclass
from dataclasses import dataclass

@dataclass
class Bar:
    a :str

b = Bar(None)

schema = marshmallow_dataclass.class_schema(Bar)
print((schema().dump(b)))
```

The output is 

`{'a': None}`

Even though the field is not Optional

**Comment by lovasoa** [comment]
Hello,
  This is not a bug. The problem in this code is the statement `Bar(None)`. It is independent of marshmallow or marshmallow-dataclass.

In python, it's the responsibility  of the programmer to follow his own type annotations. Python does not do type checking at runtime. If you want you can use mypy, that will happily warn you about this invalid code.
