### ISSUE TITLE
`{'_schema': ['Invalid input type.']}` when nesting instantiated schemas.

### ISSUE THREAD

**Issue by ifiddes** [lovasoa/marshmallow_dataclass#96]
I am using the `class.Schema().load(dict)` method of building my objects. If I have a nested object that is instantiated, it does not work:

```
from marshmallow_dataclass import dataclass
from typing import List

@dataclass
class Inner:
    val: int
        
@dataclass
class Outer:
    name: str
    vals: List[Inner]

vals = [Inner(1), Inner(2)]
o = Outer.Schema().load({"name": "n", "vals": vals})
```

Leads to

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-12-1d36df375886> in <module>
----> 1 o = Outer.Schema().load({"name": "n", "vals": vals})

~/miniconda3/envs/igs/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py in load(self, data, many, **kwargs)
    471     class BaseSchema(base_schema or marshmallow.Schema):  # type: ignore
    472         def load(self, data: Mapping, *, many: bool = None, **kwargs):
--> 473             all_loaded = super().load(data, many=many, **kwargs)
    474             many = self.many if many is None else bool(many)
    475             if many:

~/miniconda3/envs/igs/lib/python3.7/site-packages/marshmallow/schema.py in load(self, data, many, partial, unknown)
    722         """
    723         return self._do_load(
--> 724             data, many=many, partial=partial, unknown=unknown, postprocess=True
    725         )
    726 

~/miniconda3/envs/igs/lib/python3.7/site-packages/marshmallow/schema.py in _do_load(self, data, many, partial, unknown, postprocess)
    903             exc = ValidationError(errors, data=data, valid_data=result)
    904             self.handle_error(exc, data, many=many, partial=partial)
--> 905             raise exc
    906 
    907         return result

ValidationError: {'vals': {0: {'_schema': ['Invalid input type.']}, 1: {'_schema': ['Invalid input type.']}}}
```

However,

```
o = Outer(name="n", vals=vals)
```

Works fine. But, that method makes the PyCharm static checker upset:

![image](https://user-images.githubusercontent.com/7818077/90801914-5f1a0280-e2cb-11ea-8842-103fdd729608.png)

**Comment by lovasoa** [comment]
Hello,
  Schema.load expects serialized values, not a mixture of serialized and raw objects as in your example. 

  Your second example, `Outer(name="n", vals=vals)`,  is correct. PyCharm probably has a special handling of dataclasses.dataclass that doesn't work with marshmallow_dataclass.dataclass. The code is correct, the warning can be safely ignored. If you want to get rid of it, you can create a normal dataclass, and create the schema separately. Refer to the readme.

**Comment by kristian-lindin** [comment]
This happened to me as well. it happens runtime, so something seems weird when load fails on the _schema being "invalid input type"

**Comment by kristian-lindin** [comment]
Nevermid.. I got this issue when forgetting to return the mutated data from my pre_load func. Sorry!
 
@marshmallow.pre_load
    def pre_load(self, data, **kwargs):
        data["some_data"] = data.pop("someData")
       
        (Had forgotten this return statement)
        return data
