### ISSUE TITLE
typing.Set is not supported

### ISSUE THREAD

**Issue by beruic** [lovasoa/marshmallow_dataclass#99]
```python
@add_schema
@dataclass
class Stuff:
    id: str
    items: Set[str]
```

The above fails with `TypeError: typing.Set[str] is not a dataclass and cannot be turned into one.`

I often use sets to ensure de-duplication, so it would be nice if it actually constructed a `set` every time.

**Comment by lovasoa** [comment]
Marshmallow doesn't support Sets yet. See https://github.com/marshmallow-code/marshmallow/issues/1549

**Comment by beruic** [comment]
@lovasoa I guess we can close this then :)

**Comment by lovasoa** [comment]
let's keep this open. Once the feature is implemented in marshmallow and we check it works with marshmallow dataclass, we'll close this.

**Comment by carstencodes** [comment]
Sounds good. I'm using some classes that are pure readonly and must only be read.

Therefore, could you add typing.FrozenSet ?

**Comment by lovasoa** [comment]
Same as above, the support should come from marshmallow

**Comment by carstencodes** [comment]
Sure, but the original request was about typing.Set. I just wanted to add the need for frozensets.

By the way: Merry Christmas

**Comment by mivade** [comment]
As a workaround (not for sets, but for the frozen aspect) you should be able to specify `frozen=False` in the `dataclass` decorator. Of course this only works if you want every member of the instance to be immutable.
